spring:
  application:
    name: Ejemplo-Api
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
  datasource:
    url: jdbc:mariadb://localhost:3307/lenguajes
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
server:
  port: 8081
  error:
    include-message: always
logging:
  level:
    com.example.SpringBoot: DEBUG
management.endpoints.web.exposure.include: '*'